# Generated by Django 4.0.4 on 2022-05-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='web'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(verbose_name='Publicado/No Publicado ')),
                ('fecha_creaion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
