# Generated by Django 4.0.4 on 2022-05-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creaion',
            new_name='fecha_creacion',
        ),
    ]
